import type { Metadata } from 'next'
import '@/assets/globals.css'
import Footer from '@/components/common/Footer'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      {/* 所有元素要包裹在 body 裡面 */}
      <body className={`antialiased`}>
        <div className='.main'>
          {children}
        </div>
        <Footer/>
      </body>
    </html>
  )
}
